project:
  type: website
  output-dir: docs
  resources:
    - "projects/bariloche/images/slices/*.jpeg"

website:
  #title: "Santiago Zuniga"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: projects/bariloche/index.qmd
        text: Bariloche Urban Wind

format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true
    lightbox: true